"""
Workflow templates — parametrised one-shots for common FDMNES pipelines.

Each template returns a fully-formed `_inp.txt` text, optionally writes it to
a working directory, and optionally pairs it with an `fdmfile.txt`. The
caller can then launch with `fdmnes_run(working_dir=...)`.
"""
from __future__ import annotations

from pathlib import Path
from typing import Any

from .authoring_tools import fdmnes_build_input


def _scaffold(working_dir: str, inp_text: str, job_name: str) -> dict[str, Any]:
    """Write inp file + fdmfile.txt; return paths."""
    wd = Path(working_dir).expanduser().resolve()
    wd.mkdir(parents=True, exist_ok=True)
    inp = wd / f"{job_name}_inp.txt"
    inp.write_text(inp_text)
    (wd / "fdmfile.txt").write_text(
        f"! generated by fdmnes-mcp template\n 1\n{inp.name}\n"
    )
    return {
        "working_dir": str(wd),
        "input_path": str(inp),
        "fdmfile_path": str(wd / "fdmfile.txt"),
    }


def fdmnes_template_xanes(
    *,
    working_dir: str,
    job_name: str,
    structure_kind: str,
    structure_args: list[str],
    atoms: list[list],
    radius: float = 5.0,
    edge: str = "K1",
    z_absorber: int | None = None,
    energy_range: list[float] | None = None,
    method: str = "ms",
    quadrupole: bool = False,
) -> dict[str, Any]:
    """Scaffold a basic XANES job (no SCF).

    Args:
      working_dir: where to drop the `_inp.txt` and `fdmfile.txt`.
      job_name: used for the file name and the `Filout` prefix.
      structure_kind: 'crystal' | 'molecule' | 'cif_file' | 'pdb_file'.
      structure_args: cell params (a b c α β γ) or single filename for cif/pdb.
      atoms: atom rows (Z x y z), ignored for cif/pdb.
      radius: cluster radius (Å). Recommended 5-7 for production.
      edge: edge ('K', 'K1', 'L23', 'M45', ...).
      z_absorber: atomic number of absorber. If None, FDMNES uses first atom.
      energy_range: e.g. [-5, 0.5, 60]. Default if None.
      method: 'ms' (Green) or 'fdm' (default; no `Green` keyword).
      quadrupole: enable E2 multipole channel (recommended for K of 3d/4d/5d
        and L23 of heavy elements).

    Returns: {working_dir, input_path, fdmfile_path, inp_text}.
    """
    extras: dict = {}
    if method.lower() == "ms":
        extras["Green"] = None
    if quadrupole:
        extras["Quadrupole"] = None
    built = fdmnes_build_input(
        filout=f"{job_name}",
        structure_kind=structure_kind,
        structure_args=structure_args,
        atoms=atoms,
        radius=radius,
        energy_range=energy_range,
        edge=edge,
        z_absorber=z_absorber,
        extra_keywords=extras,
        convolution=True,
    )
    if "error" in built:
        return built
    paths = _scaffold(working_dir, built["text"], job_name)
    paths["inp_text"] = built["text"]
    return paths


def fdmnes_template_scf_xanes(
    *,
    working_dir: str,
    job_name: str,
    structure_kind: str,
    structure_args: list[str],
    atoms: list[list],
    radius: float = 5.0,
    edge: str = "K1",
    z_absorber: int | None = None,
    energy_range: list[float] | None = None,
    method: str = "ms",
    quadrupole: bool = True,
    density: bool = True,
    hubbard_u: float | None = None,
) -> dict[str, Any]:
    """XANES with SCF self-consistency (and optional Hubbard U).

    Adds `SCF` and optionally `Hubbard <U>` to the basic XANES template.
    Use for oxides / strongly correlated systems.

    Args: same as `fdmnes_template_xanes`, plus:
      density: emit `Density` for projected DOS output.
      hubbard_u: U-J value in eV (per atom type). None → no Hubbard.
    """
    extras: dict = {"SCF": None}
    if method.lower() == "ms":
        extras["Green"] = None
    if quadrupole:
        extras["Quadrupole"] = None
    if density:
        extras["Density"] = None
    if hubbard_u is not None:
        extras["Hubbard"] = str(hubbard_u)
    built = fdmnes_build_input(
        filout=f"{job_name}",
        structure_kind=structure_kind,
        structure_args=structure_args,
        atoms=atoms,
        radius=radius,
        energy_range=energy_range,
        edge=edge,
        z_absorber=z_absorber,
        extra_keywords=extras,
        convolution=True,
    )
    if "error" in built:
        return built
    paths = _scaffold(working_dir, built["text"], job_name)
    paths["inp_text"] = built["text"]
    return paths


def fdmnes_template_fdmx_exafs(
    *,
    working_dir: str,
    job_name: str,
    structure_kind: str,
    structure_args: list[str],
    atoms: list[list],
    edge: str = "K1",
    z_absorber: int | None = None,
    energy_range: list[float] | None = None,
    e_cut: float = -1.5,
) -> dict[str, Any]:
    """EXAFS-range XANES via FDMX. K-edge only (other edges need extra knobs).

    FDMX picks an energy-dependent radius automatically — we don't set
    `Radius`. Recommended energy range goes ~500 eV above edge.

    Args:
      e_cut: cutoff energy (eV) below which sigma → 0.

    Returns: scaffold paths.
    """
    if energy_range is None:
        energy_range = [-10.0, 0.5, 30.0, 1.0, 200.0, 2.0, 500.0]
    extras = {"FDMX": None, "E_cut": str(e_cut)}
    built = fdmnes_build_input(
        filout=f"{job_name}",
        structure_kind=structure_kind,
        structure_args=structure_args,
        atoms=atoms,
        radius=5.0,  # FDMX overrides anyway; field still required by builder
        energy_range=energy_range,
        edge=edge,
        z_absorber=z_absorber,
        extra_keywords=extras,
        convolution=True,
    )
    if "error" in built:
        return built
    paths = _scaffold(working_dir, built["text"], job_name)
    paths["inp_text"] = built["text"]
    paths["note"] = (
        "FDMX overrides Radius internally with an energy-dependent schedule. "
        "K-edge only; for L/M edges supply Gamma_hole AND noBG."
    )
    return paths


def fdmnes_template_rxs(
    *,
    working_dir: str,
    job_name: str,
    structure_kind: str,
    structure_args: list[str],
    atoms: list[list],
    edge: str = "K1",
    radius: float = 5.0,
    reflections: list[str] | None = None,
    quadrupole: bool = True,
    self_abs: bool = True,
    spherical: bool = False,
) -> dict[str, Any]:
    """Resonant X-ray scattering (DAFS) with one or more reflections.

    Args:
      reflections: list of strings, each is a DAFS row. E.g.
        ['1 1 1 1 1 0.', '1 1 1 1 2'] (h k l + polarisation codes [+azimuth]).
        Omitting the azimuth → full azimuthal scan (2°step). Polarisation
        codes: 1=sigma, 2=pi, 3=circ right, 4=circ left.
      self_abs: enable `Self_abs` (linear absorption correction).
      spherical: enable `Spherical` tensor decomposition.

    Returns: scaffold paths.
    """
    if not reflections:
        reflections = ["1 1 1 1 1 0."]
    extras: dict = {"Green": None, "DAFS": reflections}
    if quadrupole:
        extras["Quadrupole"] = None
    if self_abs:
        extras["Self_abs"] = None
    if spherical:
        extras["Spherical"] = None
    built = fdmnes_build_input(
        filout=f"{job_name}",
        structure_kind=structure_kind,
        structure_args=structure_args,
        atoms=atoms,
        radius=radius,
        edge=edge,
        extra_keywords=extras,
        convolution=True,
    )
    if "error" in built:
        return built
    paths = _scaffold(working_dir, built["text"], job_name)
    paths["inp_text"] = built["text"]
    return paths


def fdmnes_template_xmcd(
    *,
    working_dir: str,
    job_name: str,
    structure_kind: str,
    structure_args: list[str],
    atoms: list[list],
    edge: str = "L23",
    radius: float = 5.0,
    spin_orbit: bool = True,
    quadrupole: bool = False,
    polarisation: str = "0 0 0 0 0 1",
) -> dict[str, Any]:
    """Magnetic / XMCD calculation.

    Generates an input with `Magnetism` (and optionally `Spinorbite`) and a
    circular polarisation line. NOTE: the atoms list must provide per-spin
    orbital populations in the `Atom` block separately — this template only
    scaffolds the rest. Add an `Atom` block via `extra_keywords` if needed.

    Args:
      spin_orbit: include `Spinorbite` keyword (required for K-edge XMCD).
      quadrupole: enable E2 channel.
      polarisation: a Polarize row; default is circular `0 0 0 0 0 1`.

    Returns: scaffold paths.
    """
    extras: dict = {
        "Green": None,
        "Magnetism": None,
        "Polarisation": polarisation,
    }
    if spin_orbit:
        extras["Spinorbite"] = None
    if quadrupole:
        extras["Quadrupole"] = None
    built = fdmnes_build_input(
        filout=f"{job_name}",
        structure_kind=structure_kind,
        structure_args=structure_args,
        atoms=atoms,
        radius=radius,
        edge=edge,
        extra_keywords=extras,
        convolution=True,
    )
    if "error" in built:
        return built
    paths = _scaffold(working_dir, built["text"], job_name)
    paths["inp_text"] = built["text"]
    paths["note"] = (
        "For real XMCD calculations you'll likely also want a custom Atom "
        "block with per-spin orbital populations. Add it via the "
        "extra_keywords path in fdmnes_build_input."
    )
    return paths
